# @immonex/doc-gen Konfiguration
# Docs: https://docs.immonex.de/doc-gen
# Source: https://npm.immonex.de/#/detail/@immonex/doc-gen
# Docsify-Konfiguration: https://docsify.js.org/#/configuration

title: Kickstart
subtitle: immonex Kickstart
description: Essenzielle Basiskomponenten und Framework zur Einbindung und Suche/Filterung OpenImmo®-basierter Immobilienangebote
keywords:
  - wordpress
  - plugin
  - immobilien
  - immonex
  - kickstart
author: Carsten Scheuer

## Name unter welchen Verzeichnis die Doku erreichbar ist, z. B. 'doc-gen" -> https://docs.immonex.de/doc-gen'
name: kickstart

## Bestimmt ob die publizierte Dokumentation öffentlich aufrufbar ist. (public/private)
permission: public

## Dient zur Kategorisierung in der Projektliste (https://docs.immonex.de/projects)
category: Plugins

# "-" vor der Bezeichnung deaktiviert das Standardmodul
use:
  - -zoomImage
